[main][jue sep 01 14:38:06.266 2011][ERROR][com.novatronic.pool.ObjectPooledAbs:execute:202]Objeto conexion [1549556828] reporta excepcion en ejecucion
com.novatronic.components.sixclient.tcp.exception.ClienteSIXConnectionException: SIX010 - Pool[SIX] ConnSIX[[1549556828]] Timeout al esperar respuesta del SIX, maxima espera de lectura [8]seg. Datos ejecucion: [01AC0500Emp0001    01SUX     20110901143757NOVATRONIC  75382700112233       0151487            25                             00000002999000901                                         01]. Informe al productor del servicio de la demora.
	at com.novatronic.components.sixclient.tcp.ClienteSIXConnection.customExecute(ClienteSIXConnection.java:197)
	at com.novatronic.pool.ObjectPooledAbs.execute(ObjectPooledAbs.java:195)
	at com.novatronic.apiclientesixsecurityadvance.SixSecurityClientImpl.execute(SixSecurityClientImpl.java:154)
	at com.novatronic.apiclientesixsecurityadvance.SixSecurityClientImpl.consultarCoordenadas(SixSecurityClientImpl.java:1084)
	at pe.cosapi.wilder.test.TestSolicitaCoordena.main(TestSolicitaCoordena.java:114)
Caused by: 
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:155)
	at java.net.SocketInputStream.read(SocketInputStream.java:211)
	at java.io.DataInputStream.readShort(DataInputStream.java:310)
	at com.novatronic.components.sixclient.tcp.ClienteSIXConnection.leerMsg(ClienteSIXConnection.java:580)
	at com.novatronic.components.sixclient.tcp.ClienteSIXConnection.customExecute(ClienteSIXConnection.java:159)
	... 4 more
[main][jue sep 01 14:38:06.297 2011][ERROR][com.novatronic.pool.ObjectPooledAbs:execute:228]633453[1549556828] Ejecutado CON ERROR input[ID[633453]VALUE[186][01AC0500Emp0001    01SUX     20110901143757NOVATRONIC  75382700112233       0151487            25                             00000002999000901                                         01]] output[null]
[main][jue sep 01 14:38:22.787 2011][ERROR][com.novatronic.pool.PoolConnection:destroy:462]No pudo cerrar correctamente el objeto [1549556828] en la posicion [0] del pool
com.novatronic.components.sixclient.tcp.exception.ClienteSIXConnectionException: Comando Respondido no esperado recibido[SCJSSA  ] esperado[LOGOFF  ].
	at com.novatronic.components.sixclient.tcp.ClienteSIXConnection.validarRespuesta(ClienteSIXConnection.java:605)
	at com.novatronic.components.sixclient.tcp.ClienteSIXConnection.destroyObject(ClienteSIXConnection.java:285)
	at com.novatronic.pool.PoolConnection.destroyObject(PoolConnection.java:236)
	at com.novatronic.pool.PoolConnection.destroy(PoolConnection.java:460)
	at com.novatronic.pool.PoolConnection.destroy(PoolConnection.java:483)
	at com.novatronic.components.sixclient.tcp.ClienteSIXConnectionFactory.destroy(ClienteSIXConnectionFactory.java:142)
	at com.novatronic.apiclientesixsecurityadvance.SixSecurityClientImpl.destroyFactory(SixSecurityClientImpl.java:128)
	at pe.cosapi.wilder.test.TestSolicitaCoordena.main(TestSolicitaCoordena.java:146)
